// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.2.0
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void fan_rotate_Animation(lv_obj_t * TargetObject, int delay);
void fan_static_Animation(lv_obj_t * TargetObject, int delay);
void alarm_opacity_Animation(lv_obj_t * TargetObject, int delay);
void ui_event_LoadingScreen(lv_event_t * e);
lv_obj_t * ui_LoadingScreen;
lv_obj_t * ui_LabelIniciando;
lv_obj_t * ui_SpinnerIniciando;
void ui_event_ConfigScreen(lv_event_t * e);
lv_obj_t * ui_ConfigScreen;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_LabelFreqValue1;
void ui_event_btnInfo(lv_event_t * e);
lv_obj_t * ui_btnInfo;
lv_obj_t * ui_panelApplyCancelButtons;
void ui_event_btnCancel(lv_event_t * e);
lv_obj_t * ui_btnCancel;
void ui_event_btnApply(lv_event_t * e);
lv_obj_t * ui_btnApply;
lv_obj_t * ui_lblTitlePotencia;
lv_obj_t * ui_panelRollersFreq;
lv_obj_t * ui_rollerFreq1;
lv_obj_t * ui_lblDotFreq;
lv_obj_t * ui_rollerFreq2;
void ui_event_btnAjustarFreq(lv_event_t * e);
lv_obj_t * ui_btnAjustarFreq;
lv_obj_t * ui_lblBtnAjustarFreq;
lv_obj_t * ui_panelSliderPotencia;
void ui_event_SliderPotDir(lv_event_t * e);
lv_obj_t * ui_SliderPotDir;
lv_obj_t * ui_LabelPotValue;
lv_obj_t * ui_swMPX;
lv_obj_t * ui_LabelPotValue1;
lv_obj_t * ui_LabelPotValue2;
lv_obj_t * ui_MainScreen;
lv_obj_t * ui_PanelVuContainer;
lv_obj_t * ui_PanelModR;
lv_obj_t * ui_LabelModR;
lv_obj_t * ui_SliderModR;
lv_obj_t * ui_PanelModL;
lv_obj_t * ui_LabelModL;
lv_obj_t * ui_SliderModL;
lv_obj_t * ui_PanelModMPX;
lv_obj_t * ui_LabelModMPX;
lv_obj_t * ui_SliderModMPX;
lv_obj_t * ui_PanelPotRef;
lv_obj_t * ui_LabelPotRef;
lv_obj_t * ui_LabelPotRefValue;
lv_obj_t * ui_PanelPotDir;
lv_obj_t * ui_LabelPotDir;
lv_obj_t * ui_LabelPotDirValue;
lv_obj_t * ui_PanelFreqContainer;
lv_obj_t * ui_LabelFreqValue;
lv_obj_t * ui_LabelMHz;
lv_obj_t * ui_LabelMHz1;
lv_obj_t * ui_PanelIconsContainer;
lv_obj_t * ui_ButtonConfig;
void ui_event_ImgButton3(lv_event_t * e);
lv_obj_t * ui_ImgButton3;
lv_obj_t * ui_LabelTemperatureValue;
lv_obj_t * ui_ImageAlarm;
lv_obj_t * ui_ImageTemperature;
lv_obj_t * ui_ImageFan;
void ui_event_AboutScreen(lv_event_t * e);
lv_obj_t * ui_AboutScreen;
void ui_event_ImgButton5(lv_event_t * e);
lv_obj_t * ui_ImgButton5;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void fan_rotate_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_angle);
    lv_anim_set_values(&PropertyAnimation_0, 0, 3600);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_angle);
    lv_anim_start(&PropertyAnimation_0);

}
void fan_static_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 2000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_angle);
    lv_anim_set_values(&PropertyAnimation_0, 0, 3600);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_overshoot);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_angle);
    lv_anim_start(&PropertyAnimation_0);

}
void alarm_opacity_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 800);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 0, 255);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_in);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 400);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_opacity);
    lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_LoadingScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(ui_MainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 3000);
    }
}
void ui_event_ConfigScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_READY) {
        _ui_state_modify(ui_rollerFreq1, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_rollerFreq2, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
    }
}
void ui_event_btnInfo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_AboutScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
    }
}
void ui_event_btnCancel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_MainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
    }
}
void ui_event_btnApply(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_MainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
    }
}
void ui_event_btnAjustarFreq(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_label_set_property(ui_lblBtnAjustarFreq, _UI_LABEL_PROPERTY_TEXT, "ACEPTAR");
        _ui_state_modify(ui_rollerFreq1, LV_STATE_USER_1, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_rollerFreq1, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_rollerFreq2, LV_STATE_USER_1, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_rollerFreq2, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_label_set_property(ui_lblBtnAjustarFreq, _UI_LABEL_PROPERTY_TEXT, "AJUSTAR FREQ.");
        _ui_state_modify(ui_rollerFreq1, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_rollerFreq1, LV_STATE_USER_1, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_rollerFreq2, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_rollerFreq2, LV_STATE_USER_1, _UI_MODIFY_STATE_REMOVE);
    }
}
void ui_event_SliderPotDir(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_LabelPotValue, target, "", " W");
    }
}
void ui_event_ImgButton3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_ConfigScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
    }
}
void ui_event_AboutScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(ui_MainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 3000);
    }
}
void ui_event_ImgButton5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_ConfigScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
    }
}

///////////////////// SCREENS ////////////////////
void ui_LoadingScreen_screen_init(void)
{
    ui_LoadingScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_LoadingScreen, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK |
                      LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LoadingScreen, lv_color_hex(0x4C4E5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LoadingScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_LoadingScreen, lv_color_hex(0x393B46), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_LoadingScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_LoadingScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_LoadingScreen, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LoadingScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_LoadingScreen, lv_color_hex(0xD41BD2), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_LoadingScreen, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_LoadingScreen, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_LoadingScreen, 50, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelIniciando = lv_label_create(ui_LoadingScreen);
    lv_obj_set_width(ui_LabelIniciando, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelIniciando, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelIniciando, 0);
    lv_obj_set_y(ui_LabelIniciando, -57);
    lv_obj_set_align(ui_LabelIniciando, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelIniciando, "INICIANDO...");
    lv_obj_set_style_text_color(ui_LabelIniciando, lv_color_hex(0x50FF7D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelIniciando, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelIniciando, &ui_font_Kanit, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpinnerIniciando = lv_spinner_create(ui_LoadingScreen, 1000, 90);
    lv_obj_set_width(ui_SpinnerIniciando, 80);
    lv_obj_set_height(ui_SpinnerIniciando, 80);
    lv_obj_set_x(ui_SpinnerIniciando, -3);
    lv_obj_set_y(ui_SpinnerIniciando, 42);
    lv_obj_set_align(ui_SpinnerIniciando, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SpinnerIniciando, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    lv_obj_add_event_cb(ui_LoadingScreen, ui_event_LoadingScreen, LV_EVENT_ALL, NULL);

}
void ui_ConfigScreen_screen_init(void)
{
    ui_ConfigScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ConfigScreen, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_style_bg_color(ui_ConfigScreen, lv_color_hex(0x4C4E5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConfigScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ConfigScreen, lv_color_hex(0x393B46), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_ConfigScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_ConfigScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ConfigScreen, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ConfigScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ConfigScreen, lv_color_hex(0xD41BD2), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_ConfigScreen, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_ConfigScreen, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_ConfigScreen, 50, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Panel4 = lv_obj_create(ui_ConfigScreen);
    lv_obj_set_width(ui_Panel4, 437);
    lv_obj_set_height(ui_Panel4, 292);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x272A33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelFreqValue1 = lv_label_create(ui_ConfigScreen);
    lv_obj_set_width(ui_LabelFreqValue1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFreqValue1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelFreqValue1, -86);
    lv_obj_set_y(ui_LabelFreqValue1, -134);
    lv_obj_set_align(ui_LabelFreqValue1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelFreqValue1, "FRECUENCIA");
    lv_obj_set_style_text_color(ui_LabelFreqValue1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelFreqValue1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelFreqValue1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnInfo = lv_imgbtn_create(ui_ConfigScreen);
    lv_imgbtn_set_src(ui_btnInfo, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_btn_sq_info_inact_png, NULL);
    lv_imgbtn_set_src(ui_btnInfo, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_btn_sq_info_act_png, NULL);
    lv_obj_set_height(ui_btnInfo, 68);
    lv_obj_set_width(ui_btnInfo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_btnInfo, 186);
    lv_obj_set_y(ui_btnInfo, 115);
    lv_obj_set_align(ui_btnInfo, LV_ALIGN_CENTER);

    ui_panelApplyCancelButtons = lv_obj_create(ui_ConfigScreen);
    lv_obj_set_height(ui_panelApplyCancelButtons, 66);
    lv_obj_set_width(ui_panelApplyCancelButtons, lv_pct(37));
    lv_obj_set_x(ui_panelApplyCancelButtons, 0);
    lv_obj_set_y(ui_panelApplyCancelButtons, 118);
    lv_obj_set_align(ui_panelApplyCancelButtons, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_panelApplyCancelButtons, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_panelApplyCancelButtons, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_panelApplyCancelButtons, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_panelApplyCancelButtons, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panelApplyCancelButtons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_panelApplyCancelButtons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_panelApplyCancelButtons, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_panelApplyCancelButtons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_panelApplyCancelButtons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_panelApplyCancelButtons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_panelApplyCancelButtons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_panelApplyCancelButtons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnCancel = lv_imgbtn_create(ui_panelApplyCancelButtons);
    lv_imgbtn_set_src(ui_btnCancel, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_btn_sq_cancel_inact_png, NULL);
    lv_imgbtn_set_src(ui_btnCancel, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_btn_sq_cancel_act_png, NULL);
    lv_obj_set_height(ui_btnCancel, 68);
    lv_obj_set_width(ui_btnCancel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_btnCancel, 107);
    lv_obj_set_y(ui_btnCancel, 25);
    lv_obj_set_align(ui_btnCancel, LV_ALIGN_CENTER);

    ui_btnApply = lv_imgbtn_create(ui_panelApplyCancelButtons);
    lv_imgbtn_set_src(ui_btnApply, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_btn_sq_check_inact_png, NULL);
    lv_imgbtn_set_src(ui_btnApply, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_btn_sq_check_act_png, NULL);
    lv_obj_set_height(ui_btnApply, 68);
    lv_obj_set_width(ui_btnApply, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_btnApply, 110);
    lv_obj_set_y(ui_btnApply, 25);
    lv_obj_set_align(ui_btnApply, LV_ALIGN_CENTER);

    ui_lblTitlePotencia = lv_label_create(ui_ConfigScreen);
    lv_obj_set_width(ui_lblTitlePotencia, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTitlePotencia, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblTitlePotencia, 0);
    lv_obj_set_y(ui_lblTitlePotencia, 53);
    lv_obj_set_align(ui_lblTitlePotencia, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblTitlePotencia, "POTENCIA");
    lv_obj_set_style_text_color(ui_lblTitlePotencia, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblTitlePotencia, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblTitlePotencia, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panelRollersFreq = lv_obj_create(ui_ConfigScreen);
    lv_obj_set_width(ui_panelRollersFreq, 240);
    lv_obj_set_height(ui_panelRollersFreq, 115);
    lv_obj_set_x(ui_panelRollersFreq, -86);
    lv_obj_set_y(ui_panelRollersFreq, -83);
    lv_obj_set_align(ui_panelRollersFreq, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_panelRollersFreq, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_panelRollersFreq, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_panelRollersFreq, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_panelRollersFreq, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panelRollersFreq, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panelRollersFreq, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panelRollersFreq, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rollerFreq1 = lv_roller_create(ui_panelRollersFreq);
    lv_roller_set_options(ui_rollerFreq1,
                          "88\n89\n90\n91\n92\n93\n94\n95\n96\n97\n98\n99\n100\n101\n102\n103\n104\n105\n106\n107\n108", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_rollerFreq1, 76);
    lv_obj_set_height(ui_rollerFreq1, 91);
    lv_obj_set_x(ui_rollerFreq1, -47);
    lv_obj_set_y(ui_rollerFreq1, -79);
    lv_obj_set_align(ui_rollerFreq1, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_rollerFreq1, LV_STATE_DISABLED);       /// States
    lv_obj_set_style_text_color(ui_rollerFreq1, lv_color_hex(0x50FF7D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rollerFreq1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rollerFreq1, lv_color_hex(0x202831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rollerFreq1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_rollerFreq1, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rollerFreq1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_rollerFreq1, lv_color_hex(0xD70B0B), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_border_opa(ui_rollerFreq1, 255, LV_PART_MAIN | LV_STATE_USER_1);

    lv_obj_set_style_text_font(ui_rollerFreq1, &lv_font_montserrat_32, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rollerFreq1, lv_color_hex(0x2095F6), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rollerFreq1, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_lblDotFreq = lv_label_create(ui_panelRollersFreq);
    lv_obj_set_width(ui_lblDotFreq, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblDotFreq, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblDotFreq, 8);
    lv_obj_set_y(ui_lblDotFreq, -45);
    lv_obj_set_align(ui_lblDotFreq, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblDotFreq, ".");
    lv_obj_set_style_text_color(ui_lblDotFreq, lv_color_hex(0x52FF7B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblDotFreq, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblDotFreq, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rollerFreq2 = lv_roller_create(ui_panelRollersFreq);
    lv_roller_set_options(ui_rollerFreq2, "0\n1\n2\n3\n4\n5\n6\n7\n8\n9", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_rollerFreq2, 76);
    lv_obj_set_height(ui_rollerFreq2, 91);
    lv_obj_set_x(ui_rollerFreq2, 69);
    lv_obj_set_y(ui_rollerFreq2, -79);
    lv_obj_set_align(ui_rollerFreq2, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_rollerFreq2, lv_color_hex(0x50FF7D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rollerFreq2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rollerFreq2, lv_color_hex(0x202831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rollerFreq2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_rollerFreq2, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rollerFreq2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_rollerFreq2, lv_color_hex(0xC50B0C), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_border_opa(ui_rollerFreq2, 255, LV_PART_MAIN | LV_STATE_USER_1);

    lv_obj_set_style_text_font(ui_rollerFreq2, &lv_font_montserrat_32, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rollerFreq2, lv_color_hex(0x2095F6), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rollerFreq2, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_btnAjustarFreq = lv_btn_create(ui_ConfigScreen);
    lv_obj_set_width(ui_btnAjustarFreq, 131);
    lv_obj_set_height(ui_btnAjustarFreq, 33);
    lv_obj_set_x(ui_btnAjustarFreq, -83);
    lv_obj_set_y(ui_btnAjustarFreq, -8);
    lv_obj_set_align(ui_btnAjustarFreq, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnAjustarFreq, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnAjustarFreq, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnAjustarFreq, lv_color_hex(0x8B919C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnAjustarFreq, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnAjustarFreq, lv_color_hex(0x393C41), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnAjustarFreq, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblBtnAjustarFreq = lv_label_create(ui_btnAjustarFreq);
    lv_obj_set_width(ui_lblBtnAjustarFreq, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblBtnAjustarFreq, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblBtnAjustarFreq, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblBtnAjustarFreq, "AJUSTAR FREQ.");

    ui_panelSliderPotencia = lv_obj_create(ui_ConfigScreen);
    lv_obj_set_width(ui_panelSliderPotencia, 401);
    lv_obj_set_height(ui_panelSliderPotencia, 56);
    lv_obj_set_x(ui_panelSliderPotencia, 0);
    lv_obj_set_y(ui_panelSliderPotencia, 75);
    lv_obj_set_align(ui_panelSliderPotencia, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_panelSliderPotencia, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_panelSliderPotencia, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_panelSliderPotencia, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_panelSliderPotencia, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panelSliderPotencia, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panelSliderPotencia, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panelSliderPotencia, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderPotDir = lv_slider_create(ui_panelSliderPotencia);
    lv_slider_set_range(ui_SliderPotDir, 0, 300);
    lv_slider_set_value(ui_SliderPotDir, 10, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderPotDir) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderPotDir, 0,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderPotDir, 291);
    lv_obj_set_height(ui_SliderPotDir, 10);
    lv_obj_set_x(ui_SliderPotDir, 3);
    lv_obj_set_y(ui_SliderPotDir, 53);
    lv_obj_set_align(ui_SliderPotDir, LV_ALIGN_CENTER);

    ui_LabelPotValue = lv_label_create(ui_panelSliderPotencia);
    lv_obj_set_width(ui_LabelPotValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPotValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPotValue, 0);
    lv_obj_set_y(ui_LabelPotValue, 75);
    lv_obj_set_align(ui_LabelPotValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPotValue, "60 W");
    lv_obj_set_style_text_color(ui_LabelPotValue, lv_color_hex(0x52FF7B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPotValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPotValue, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_swMPX = lv_switch_create(ui_ConfigScreen);
    lv_obj_set_width(ui_swMPX, 96);
    lv_obj_set_height(ui_swMPX, 48);
    lv_obj_set_x(ui_swMPX, 129);
    lv_obj_set_y(ui_swMPX, -71);
    lv_obj_set_align(ui_swMPX, LV_ALIGN_CENTER);

    ui_LabelPotValue1 = lv_label_create(ui_ConfigScreen);
    lv_obj_set_width(ui_LabelPotValue1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPotValue1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPotValue1, 69);
    lv_obj_set_y(ui_LabelPotValue1, -21);
    lv_obj_set_align(ui_LabelPotValue1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPotValue1, "ST");
    lv_obj_set_style_text_color(ui_LabelPotValue1, lv_color_hex(0x52FF7B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPotValue1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPotValue1, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPotValue2 = lv_label_create(ui_ConfigScreen);
    lv_obj_set_width(ui_LabelPotValue2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPotValue2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPotValue2, 173);
    lv_obj_set_y(ui_LabelPotValue2, -21);
    lv_obj_set_align(ui_LabelPotValue2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPotValue2, "MPX");
    lv_obj_set_style_text_color(ui_LabelPotValue2, lv_color_hex(0x52FF7B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPotValue2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPotValue2, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnInfo, ui_event_btnInfo, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnCancel, ui_event_btnCancel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnApply, ui_event_btnApply, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnAjustarFreq, ui_event_btnAjustarFreq, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderPotDir, ui_event_SliderPotDir, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ConfigScreen, ui_event_ConfigScreen, LV_EVENT_ALL, NULL);

}
void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainScreen, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK |
                      LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainScreen, lv_color_hex(0x4C4E5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_MainScreen, lv_color_hex(0x393B46), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_MainScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_MainScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_MainScreen, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MainScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_MainScreen, lv_color_hex(0xD41BD2), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_MainScreen, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_MainScreen, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_MainScreen, 50, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_PanelVuContainer = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_PanelVuContainer, 327);
    lv_obj_set_height(ui_PanelVuContainer, 168);
    lv_obj_set_x(ui_PanelVuContainer, 77);
    lv_obj_set_y(ui_PanelVuContainer, 64);
    lv_obj_set_align(ui_PanelVuContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelVuContainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PanelVuContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END);
    lv_obj_clear_flag(ui_PanelVuContainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelVuContainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelVuContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelVuContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelVuContainer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelVuContainer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelVuContainer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelVuContainer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelModR = lv_obj_create(ui_PanelVuContainer);
    lv_obj_set_height(ui_PanelModR, 25);
    lv_obj_set_width(ui_PanelModR, lv_pct(88));
    lv_obj_set_align(ui_PanelModR, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelModR, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelModR, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelModR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelModR, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelModR, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelModR, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelModR = lv_label_create(ui_PanelModR);
    lv_obj_set_width(ui_LabelModR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelModR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelModR, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelModR, "R");
    lv_obj_set_style_text_color(ui_LabelModR, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelModR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderModR = lv_slider_create(ui_PanelModR);
    lv_slider_set_range(ui_SliderModR, 0, 20);
    lv_slider_set_value(ui_SliderModR, 20, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderModR) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderModR, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderModR, 190);
    lv_obj_set_height(ui_SliderModR, 24);
    lv_obj_set_x(ui_SliderModR, 116);
    lv_obj_set_y(ui_SliderModR, -54);
    lv_obj_set_align(ui_SliderModR, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SliderModR, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_radius(ui_SliderModR, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderModR, lv_color_hex(0x272A33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderModR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_SliderModR, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_SliderModR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SliderModR, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SliderModR, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SliderModR, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SliderModR, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SliderModR, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SliderModR, 4, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderModR, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderModR, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_SliderModR, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_SliderModR, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_SliderModR, &ui_img_indicator_reduced_hor_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderModR, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderModR, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_PanelModL = lv_obj_create(ui_PanelVuContainer);
    lv_obj_set_height(ui_PanelModL, 25);
    lv_obj_set_width(ui_PanelModL, lv_pct(88));
    lv_obj_set_align(ui_PanelModL, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelModL, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelModL, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelModL, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelModL, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelModL, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelModL, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelModL = lv_label_create(ui_PanelModL);
    lv_obj_set_width(ui_LabelModL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelModL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelModL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelModL, "L");
    lv_obj_set_style_text_color(ui_LabelModL, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelModL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderModL = lv_slider_create(ui_PanelModL);
    lv_slider_set_range(ui_SliderModL, 0, 20);
    lv_slider_set_value(ui_SliderModL, 20, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderModL) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderModL, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderModL, 190);
    lv_obj_set_height(ui_SliderModL, 24);
    lv_obj_set_x(ui_SliderModL, 116);
    lv_obj_set_y(ui_SliderModL, -54);
    lv_obj_set_align(ui_SliderModL, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SliderModL, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_radius(ui_SliderModL, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderModL, lv_color_hex(0x272A33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderModL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_SliderModL, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_SliderModL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SliderModL, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SliderModL, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SliderModL, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SliderModL, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SliderModL, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SliderModL, 4, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderModL, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderModL, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_SliderModL, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_SliderModL, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_SliderModL, &ui_img_indicator_reduced_hor_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderModL, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderModL, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_PanelModMPX = lv_obj_create(ui_PanelVuContainer);
    lv_obj_set_height(ui_PanelModMPX, 25);
    lv_obj_set_width(ui_PanelModMPX, lv_pct(88));
    lv_obj_set_align(ui_PanelModMPX, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelModMPX, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelModMPX, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelModMPX, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelModMPX, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelModMPX, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelModMPX, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelModMPX = lv_label_create(ui_PanelModMPX);
    lv_obj_set_width(ui_LabelModMPX, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelModMPX, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelModMPX, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelModMPX, "MPX");
    lv_obj_set_style_text_color(ui_LabelModMPX, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelModMPX, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderModMPX = lv_slider_create(ui_PanelModMPX);
    lv_slider_set_range(ui_SliderModMPX, 0, 20);
    lv_slider_set_value(ui_SliderModMPX, 20, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderModMPX) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderModMPX, 0,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderModMPX, 190);
    lv_obj_set_height(ui_SliderModMPX, 24);
    lv_obj_set_x(ui_SliderModMPX, 116);
    lv_obj_set_y(ui_SliderModMPX, -54);
    lv_obj_set_align(ui_SliderModMPX, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SliderModMPX, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_radius(ui_SliderModMPX, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderModMPX, lv_color_hex(0x272A33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderModMPX, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_SliderModMPX, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_SliderModMPX, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SliderModMPX, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SliderModMPX, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SliderModMPX, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SliderModMPX, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SliderModMPX, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SliderModMPX, 4, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderModMPX, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderModMPX, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_SliderModMPX, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_SliderModMPX, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_SliderModMPX, &ui_img_indicator_reduced_hor_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderModMPX, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderModMPX, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_PanelPotRef = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_PanelPotRef, 218);
    lv_obj_set_height(ui_PanelPotRef, 25);
    lv_obj_set_x(ui_PanelPotRef, 128);
    lv_obj_set_y(ui_PanelPotRef, 132);
    lv_obj_set_align(ui_PanelPotRef, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelPotRef, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelPotRef, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelPotRef, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelPotRef, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelPotRef, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelPotRef, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPotRef = lv_label_create(ui_PanelPotRef);
    lv_obj_set_width(ui_LabelPotRef, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPotRef, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPotRef, 0);
    lv_obj_set_y(ui_LabelPotRef, 2);
    lv_obj_set_align(ui_LabelPotRef, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPotRef, "POT REF (W)");
    lv_obj_set_style_text_color(ui_LabelPotRef, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPotRef, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPotRef, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPotRefValue = lv_label_create(ui_PanelPotRef);
    lv_obj_set_width(ui_LabelPotRefValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPotRefValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPotRefValue, 150);
    lv_obj_set_y(ui_LabelPotRefValue, 20);
    lv_obj_set_align(ui_LabelPotRefValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPotRefValue, "10");
    lv_obj_set_style_text_color(ui_LabelPotRefValue, lv_color_hex(0x52FF7B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPotRefValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPotRefValue, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_LabelPotRefValue, lv_color_hex(0xFF6B08), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_text_opa(ui_LabelPotRefValue, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_text_color(ui_LabelPotRefValue, lv_color_hex(0xFF0F08), LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_text_opa(ui_LabelPotRefValue, 255, LV_PART_MAIN | LV_STATE_USER_2);

    ui_PanelPotDir = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_PanelPotDir, 218);
    lv_obj_set_height(ui_PanelPotDir, 25);
    lv_obj_set_x(ui_PanelPotDir, 260);
    lv_obj_set_y(ui_PanelPotDir, 247);
    lv_obj_set_flex_flow(ui_PanelPotDir, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelPotDir, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelPotDir, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelPotDir, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelPotDir, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelPotDir, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPotDir = lv_label_create(ui_PanelPotDir);
    lv_obj_set_width(ui_LabelPotDir, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPotDir, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelPotDir, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPotDir, "POT DIR (W)");
    lv_obj_set_style_text_color(ui_LabelPotDir, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPotDir, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPotDir, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPotDirValue = lv_label_create(ui_PanelPotDir);
    lv_obj_set_width(ui_LabelPotDirValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPotDirValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPotDirValue, 150);
    lv_obj_set_y(ui_LabelPotDirValue, -20);
    lv_obj_set_align(ui_LabelPotDirValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPotDirValue, "120");
    lv_obj_set_style_text_color(ui_LabelPotDirValue, lv_color_hex(0x52FF7B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPotDirValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPotDirValue, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_LabelPotDirValue, lv_color_hex(0xFF6108), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_text_opa(ui_LabelPotDirValue, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_text_color(ui_LabelPotDirValue, lv_color_hex(0xFF0D08), LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_text_opa(ui_LabelPotDirValue, 255, LV_PART_MAIN | LV_STATE_USER_2);

    ui_PanelFreqContainer = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_PanelFreqContainer, 447);
    lv_obj_set_height(ui_PanelFreqContainer, 108);
    lv_obj_set_x(ui_PanelFreqContainer, 0);
    lv_obj_set_y(ui_PanelFreqContainer, -88);
    lv_obj_set_align(ui_PanelFreqContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelFreqContainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelFreqContainer, lv_color_hex(0x272A33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelFreqContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelFreqContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelFreqValue = lv_label_create(ui_PanelFreqContainer);
    lv_obj_set_width(ui_LabelFreqValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFreqValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelFreqValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelFreqValue, "101.5");
    lv_obj_set_style_text_color(ui_LabelFreqValue, lv_color_hex(0x50FF7D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelFreqValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelFreqValue, &ui_font_Kanit, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMHz = lv_label_create(ui_PanelFreqContainer);
    lv_obj_set_width(ui_LabelMHz, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMHz, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMHz, 140);
    lv_obj_set_y(ui_LabelMHz, 0);
    lv_obj_set_align(ui_LabelMHz, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMHz, "MHz");
    lv_obj_set_style_text_color(ui_LabelMHz, lv_color_hex(0x50FF7D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMHz, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMHz, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMHz1 = lv_label_create(ui_PanelFreqContainer);
    lv_obj_set_width(ui_LabelMHz1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMHz1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMHz1, -140);
    lv_obj_set_y(ui_LabelMHz1, 0);
    lv_obj_set_align(ui_LabelMHz1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMHz1, "FREQ");
    lv_obj_set_style_text_color(ui_LabelMHz1, lv_color_hex(0x50FF7D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMHz1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMHz1, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelIconsContainer = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_PanelIconsContainer, 206);
    lv_obj_set_height(ui_PanelIconsContainer, 165);
    lv_obj_set_x(ui_PanelIconsContainer, 17);
    lv_obj_set_y(ui_PanelIconsContainer, 143);
    lv_obj_clear_flag(ui_PanelIconsContainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelIconsContainer, lv_color_hex(0x272A33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelIconsContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelIconsContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonConfig = lv_obj_create(ui_PanelIconsContainer);
    lv_obj_set_height(ui_ButtonConfig, 71);
    lv_obj_set_width(ui_ButtonConfig, lv_pct(42));
    lv_obj_set_x(ui_ButtonConfig, -69);
    lv_obj_set_y(ui_ButtonConfig, 50);
    lv_obj_set_align(ui_ButtonConfig, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ButtonConfig, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ButtonConfig, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ButtonConfig, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonConfig, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonConfig, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_ButtonConfig, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_ButtonConfig, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ButtonConfig, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ButtonConfig, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ButtonConfig, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ButtonConfig, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ButtonConfig, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton3 = lv_imgbtn_create(ui_ButtonConfig);
    lv_imgbtn_set_src(ui_ImgButton3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_config_inact_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton3, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_config_act_png, NULL);
    lv_obj_set_width(ui_ImgButton3, 71);
    lv_obj_set_height(ui_ImgButton3, 68);
    lv_obj_set_x(ui_ImgButton3, 266);
    lv_obj_set_y(ui_ImgButton3, 0);
    lv_obj_set_align(ui_ImgButton3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ImgButton3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ImgButton3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

    ui_LabelTemperatureValue = lv_label_create(ui_PanelIconsContainer);
    lv_obj_set_width(ui_LabelTemperatureValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTemperatureValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTemperatureValue, 40);
    lv_obj_set_y(ui_LabelTemperatureValue, -31);
    lv_obj_set_align(ui_LabelTemperatureValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTemperatureValue, "62");
    lv_obj_set_style_text_color(ui_LabelTemperatureValue, lv_color_hex(0x50FF7D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTemperatureValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTemperatureValue, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_LabelTemperatureValue, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_LabelTemperatureValue, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_LabelTemperatureValue, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_text_opa(ui_LabelTemperatureValue, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_text_color(ui_LabelTemperatureValue, lv_color_hex(0xFF8650), LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_text_opa(ui_LabelTemperatureValue, 255, LV_PART_MAIN | LV_STATE_USER_2);

    ui_ImageAlarm = lv_img_create(ui_PanelIconsContainer);
    lv_img_set_src(ui_ImageAlarm, &ui_img_alarm_png);
    lv_obj_set_width(ui_ImageAlarm, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_ImageAlarm, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_ImageAlarm, 61);
    lv_obj_set_y(ui_ImageAlarm, 48);
    lv_obj_set_align(ui_ImageAlarm, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageAlarm, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageAlarm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageTemperature = lv_img_create(ui_PanelIconsContainer);
    lv_img_set_src(ui_ImageTemperature, &ui_img_temp_png);
    lv_obj_set_width(ui_ImageTemperature, LV_SIZE_CONTENT);   /// 70
    lv_obj_set_height(ui_ImageTemperature, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_ImageTemperature, -30);
    lv_obj_set_y(ui_ImageTemperature, -30);
    lv_obj_set_align(ui_ImageTemperature, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageTemperature, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageTemperature, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageFan = lv_img_create(ui_PanelIconsContainer);
    lv_img_set_src(ui_ImageFan, &ui_img_fan_png);
    lv_obj_set_width(ui_ImageFan, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_ImageFan, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_ImageFan, -4);
    lv_obj_set_y(ui_ImageFan, 51);
    lv_obj_set_align(ui_ImageFan, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageFan, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageFan, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_ImageFan, lv_color_hex(0x4959F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_ImageFan, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ImgButton3, ui_event_ImgButton3, LV_EVENT_ALL, NULL);

}
void ui_AboutScreen_screen_init(void)
{
    ui_AboutScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_AboutScreen, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK |
                      LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AboutScreen, lv_color_hex(0x4C4E5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AboutScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_AboutScreen, lv_color_hex(0x393B46), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_AboutScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_AboutScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_AboutScreen, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_AboutScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_AboutScreen, lv_color_hex(0xD41BD2), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_AboutScreen, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_AboutScreen, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_AboutScreen, 50, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_ImgButton5 = lv_imgbtn_create(ui_AboutScreen);
    lv_imgbtn_set_src(ui_ImgButton5, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_btn_sq_back_inact_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton5, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_btn_sq_back_act_png, NULL);
    lv_obj_set_width(ui_ImgButton5, 71);
    lv_obj_set_height(ui_ImgButton5, 68);
    lv_obj_set_x(ui_ImgButton5, -191);
    lv_obj_set_y(ui_ImgButton5, 113);
    lv_obj_set_align(ui_ImgButton5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ImgButton5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ImgButton5, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

    lv_obj_add_event_cb(ui_ImgButton5, ui_event_ImgButton5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_AboutScreen, ui_event_AboutScreen, LV_EVENT_ALL, NULL);

}

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_LoadingScreen_screen_init();
    ui_ConfigScreen_screen_init();
    ui_MainScreen_screen_init();
    ui_AboutScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_LoadingScreen);
}
