// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.2
// LVGL version: 8.2.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_events.h"
void Anim1_Animation(lv_obj_t * TargetObject, int delay);
extern lv_obj_t * ui_Screen1;
void ui_event_Panel2(lv_event_t * e);
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Roller2;
extern lv_obj_t * ui_Roller1;
extern lv_obj_t * ui_Roller4;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Slider2;
extern lv_obj_t * ui_Panel4;
void ui_event_ImgButton2(lv_event_t * e);
extern lv_obj_t * ui_ImgButton2;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Screen2;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_indicator_ver_png);    // assets\indicator_ver.png
LV_IMG_DECLARE(ui_img_btn_1_inact_png);    // assets\btn_1_inact.png
LV_IMG_DECLARE(ui_img_btn_1_act_png);    // assets\btn_1_act.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
